version: "3.0"
volumes:
  vendor:
services:
  siuccweb07:
    image: francon/phpora:2
    ports: 
        - "82:80"
    volumes:
        - ./:/var/www/html
        - ./serverconfig/nginx.conf:/etc/nginx/nginx.conf
        - ./serverconfig/entrypoint.sh:/etc/entrypoint.sh
        - vendor:/var/www/html/vendor

    command: echo "hola mundo"